/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AcpReplayEvents {
  at: number;
  run_id: string | null;
  seq: number;
  session_id: string;
  session_key: string;
  update_json: string;
}

export interface AcpReplaySessions {
  complete: number;
  created_at: number;
  cwd: string;
  next_seq: number;
  session_id: string;
  session_key: string;
  updated_at: number;
}

export interface AgentDatabases {
  agent_id: string;
  last_seen_at: number;
  path: string;
  schema_version: number;
  size_bytes: number | null;
}

export interface Agents {
  agent_id: string;
  config_json: string;
  created_at: number;
  updated_at: number;
}

export interface BackupRuns {
  archive_path: string;
  created_at: number;
  id: string;
  manifest_json: string;
  status: string;
}

export interface CaptureBlobs {
  blob_id: string;
  content_type: string | null;
  created_at: number;
  data: Uint8Array;
  encoding: string;
  sha256: string;
  size_bytes: number;
}

export interface CaptureEvents {
  close_code: number | null;
  content_type: string | null;
  data_blob_id: string | null;
  data_sha256: string | null;
  data_text: string | null;
  direction: string;
  error_text: string | null;
  flow_id: string;
  headers_json: string | null;
  host: string | null;
  id: Generated<number>;
  kind: string;
  meta_json: string | null;
  method: string | null;
  path: string | null;
  protocol: string;
  session_id: string;
  source_process: string;
  source_scope: string;
  status: number | null;
  ts: number;
}

export interface CaptureSessions {
  blob_dir: string;
  db_path: string;
  ended_at: number | null;
  id: string;
  mode: string;
  proxy_url: string | null;
  source_process: string;
  source_scope: string;
  started_at: number;
}

export interface Commitments {
  agent_id: string;
  channel: string;
  due_earliest_ms: number;
  due_latest_ms: number;
  id: string;
  record_json: string;
  session_key: string;
  status: string;
  updated_at_ms: number;
}

export interface CronJobs {
  job_id: string;
  job_json: string;
  runtime_updated_at_ms: number | null;
  schedule_identity: string | null;
  sort_order: Generated<number>;
  state_json: Generated<string>;
  store_key: string;
  updated_at: number;
}

export interface CronRunLogs {
  created_at: number;
  entry_json: string;
  job_id: string;
  seq: number;
  store_key: string;
  ts: number;
}

export interface CurrentConversationBindings {
  account_id: string;
  binding_id: string;
  binding_key: string;
  bound_at: number;
  channel: string;
  conversation_id: string;
  expires_at: number | null;
  metadata_json: string | null;
  parent_conversation_id: string | null;
  record_json: string;
  status: string;
  target_kind: string;
  target_session_key: string;
  updated_at: number;
}

export interface DeliveryQueueEntries {
  enqueued_at: number;
  entry_json: string;
  failed_at: number | null;
  id: string;
  queue_name: string;
  status: string;
  updated_at: number;
}

export interface FlowRuns {
  blocked_summary: string | null;
  blocked_task_id: string | null;
  cancel_requested_at: number | null;
  controller_id: string | null;
  created_at: number;
  current_step: string | null;
  ended_at: number | null;
  flow_id: string;
  goal: string;
  notify_policy: string;
  owner_key: string;
  requester_origin_json: string | null;
  revision: Generated<number>;
  shape: string | null;
  state_json: string | null;
  status: string;
  sync_mode: Generated<string>;
  updated_at: number;
  wait_json: string | null;
}

export interface Kv {
  key: string;
  scope: string;
  updated_at: number;
  value_json: string;
}

export interface MediaBlobs {
  blob: Uint8Array;
  content_type: string | null;
  created_at: number;
  id: string;
  size_bytes: number;
  subdir: string;
  updated_at: number;
}

export interface MigrationRuns {
  finished_at: number | null;
  id: string;
  report_json: string;
  source_version: number | null;
  started_at: number;
  status: string;
  target_version: number | null;
}

export interface MigrationSources {
  imported_at: number;
  last_run_id: string;
  migration_kind: string;
  removed_source: Generated<number>;
  report_json: string;
  source_key: string;
  source_path: string;
  source_record_count: number | null;
  source_sha256: string | null;
  source_size_bytes: number | null;
  status: string;
  target_table: string;
}

export interface PluginBlobEntries {
  blob: Uint8Array;
  created_at: number;
  entry_key: string;
  expires_at: number | null;
  metadata_json: string;
  namespace: string;
  plugin_id: string;
}

export interface PluginStateEntries {
  created_at: number;
  entry_key: string;
  expires_at: number | null;
  namespace: string;
  plugin_id: string;
  value_json: string;
}

export interface SandboxRegistryEntries {
  container_name: string;
  entry_json: string;
  registry_kind: string;
  updated_at: number;
}

export interface SchemaMigrations {
  applied_at: number;
  version: Generated<number>;
}

export interface SubagentRuns {
  accumulated_runtime_ms: number | null;
  agent_dir: string | null;
  announce_retry_count: number | null;
  archive_at_ms: number | null;
  attachments_dir: string | null;
  attachments_root_dir: string | null;
  child_session_key: string;
  cleanup: string;
  cleanup_completed_at: number | null;
  cleanup_handled: number | null;
  completion_announced_at: number | null;
  controller_session_key: string | null;
  created_at: number;
  ended_at: number | null;
  ended_hook_emitted_at: number | null;
  ended_reason: string | null;
  expects_completion_message: number | null;
  fallback_frozen_result_captured_at: number | null;
  fallback_frozen_result_text: string | null;
  frozen_result_captured_at: number | null;
  frozen_result_text: string | null;
  label: string | null;
  last_announce_delivery_error: string | null;
  last_announce_retry_at: number | null;
  model: string | null;
  outcome_json: string | null;
  pause_reason: string | null;
  payload_json: Generated<string>;
  pending_final_delivery: number | null;
  pending_final_delivery_attempt_count: number | null;
  pending_final_delivery_created_at: number | null;
  pending_final_delivery_last_attempt_at: number | null;
  pending_final_delivery_last_error: string | null;
  pending_final_delivery_payload_json: string | null;
  requester_display_key: string;
  requester_origin_json: string | null;
  requester_session_key: string;
  retain_attachments_on_keep: number | null;
  run_id: string;
  run_timeout_seconds: number | null;
  session_started_at: number | null;
  spawn_mode: string | null;
  started_at: number | null;
  suppress_announce_reason: string | null;
  task: string;
  wake_on_descendant_settle: number | null;
  workspace_dir: string | null;
}

export interface TaskDeliveryState {
  last_notified_event_at: number | null;
  requester_origin_json: string | null;
  task_id: string;
}

export interface TaskRuns {
  agent_id: string | null;
  child_session_key: string | null;
  cleanup_after: number | null;
  created_at: number;
  delivery_status: string;
  ended_at: number | null;
  error: string | null;
  label: string | null;
  last_event_at: number | null;
  notify_policy: string;
  owner_key: string;
  parent_flow_id: string | null;
  parent_task_id: string | null;
  progress_summary: string | null;
  requester_session_key: string | null;
  run_id: string | null;
  runtime: string;
  scope_kind: string;
  source_id: string | null;
  started_at: number | null;
  status: string;
  task: string;
  task_id: string;
  task_kind: string | null;
  terminal_outcome: string | null;
  terminal_summary: string | null;
}

export interface TranscriptFiles {
  agent_id: string;
  exported_at: number | null;
  imported_at: number | null;
  path: string;
  session_id: string;
}

export interface TuiLastSessions {
  scope_key: string;
  session_key: string;
  updated_at: number;
}

export interface DB {
  acp_replay_events: AcpReplayEvents;
  acp_replay_sessions: AcpReplaySessions;
  agent_databases: AgentDatabases;
  agents: Agents;
  backup_runs: BackupRuns;
  capture_blobs: CaptureBlobs;
  capture_events: CaptureEvents;
  capture_sessions: CaptureSessions;
  commitments: Commitments;
  cron_jobs: CronJobs;
  cron_run_logs: CronRunLogs;
  current_conversation_bindings: CurrentConversationBindings;
  delivery_queue_entries: DeliveryQueueEntries;
  flow_runs: FlowRuns;
  kv: Kv;
  media_blobs: MediaBlobs;
  migration_runs: MigrationRuns;
  migration_sources: MigrationSources;
  plugin_blob_entries: PluginBlobEntries;
  plugin_state_entries: PluginStateEntries;
  sandbox_registry_entries: SandboxRegistryEntries;
  schema_migrations: SchemaMigrations;
  subagent_runs: SubagentRuns;
  task_delivery_state: TaskDeliveryState;
  task_runs: TaskRuns;
  transcript_files: TranscriptFiles;
  tui_last_sessions: TuiLastSessions;
}
