/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AcpParentStreamEvents {
  created_at: number;
  event_json: string;
  run_id: string;
  seq: number;
}

export interface CacheEntries {
  blob: Buffer | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface Kv {
  key: string;
  scope: string;
  updated_at: number;
  value_json: string;
}

export interface RunArtifacts {
  blob: Buffer | null;
  created_at: number;
  kind: string;
  metadata_json: string;
  path: string;
  run_id: string;
}

export interface SchemaMigrations {
  applied_at: number;
  version: Generated<number>;
}

export interface SessionEntries {
  entry_json: string;
  session_key: string;
  updated_at: number;
}

export interface ToolArtifacts {
  artifact_id: string;
  blob: Buffer | null;
  created_at: number;
  kind: string;
  metadata_json: string;
  run_id: string;
}

export interface TrajectoryRuntimeEvents {
  created_at: number;
  event_id: Generated<number>;
  event_json: string;
  run_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEventIdentities {
  created_at: number;
  event_id: string;
  event_type: string | null;
  has_parent: Generated<number>;
  message_idempotency_key: string | null;
  parent_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEvents {
  created_at: number;
  event_json: string;
  seq: number;
  session_id: string;
}

export interface TranscriptSnapshots {
  created_at: number;
  event_count: number;
  metadata_json: string;
  reason: string;
  session_id: string;
  snapshot_id: string;
}

export interface VfsEntries {
  content_blob: Buffer | null;
  kind: string;
  metadata_json: string;
  namespace: string;
  path: string;
  updated_at: number;
}

export interface DB {
  acp_parent_stream_events: AcpParentStreamEvents;
  cache_entries: CacheEntries;
  kv: Kv;
  run_artifacts: RunArtifacts;
  schema_migrations: SchemaMigrations;
  session_entries: SessionEntries;
  tool_artifacts: ToolArtifacts;
  trajectory_runtime_events: TrajectoryRuntimeEvents;
  transcript_event_identities: TranscriptEventIdentities;
  transcript_events: TranscriptEvents;
  transcript_snapshots: TranscriptSnapshots;
  vfs_entries: VfsEntries;
}
